from django import forms
from .models import Order

class OrderCreateForm(forms.ModelForm):
	DIVISION_CHOICES = [
    ('Mumbai, Maharashtra', 'Mumbai, Maharashtra'),
    ('Pune, Maharashtra', 'Pune, Maharashtra'),
    ('Nagpur, Maharashtra', 'Nagpur, Maharashtra'),
    ('Nashik, Maharashtra', 'Nashik, Maharashtra'),
    ('Aurangabad, Maharashtra', 'Aurangabad, Maharashtra'),
    ('Bengaluru, Karnataka', 'Bengaluru, Karnataka'),
    ('Mysuru, Karnataka', 'Mysuru, Karnataka'),
    ('Hubballi, Karnataka', 'Hubballi, Karnataka'),
    ('Mangalore, Karnataka', 'Mangalore, Karnataka'),
    ('Belgaum, Karnataka', 'Belgaum, Karnataka'),
    ('Chennai, Tamil Nadu', 'Chennai, Tamil Nadu'),
    ('Coimbatore, Tamil Nadu', 'Coimbatore, Tamil Nadu'),
    ('Madurai, Tamil Nadu', 'Madurai, Tamil Nadu'),
    ('Tiruchirappalli, Tamil Nadu', 'Tiruchirappalli, Tamil Nadu'),
    ('Salem, Tamil Nadu', 'Salem, Tamil Nadu'),
    ('Kolkata, West Bengal', 'Kolkata, West Bengal'),
    ('Howrah, West Bengal', 'Howrah, West Bengal'),
    ('Durgapur, West Bengal', 'Durgapur, West Bengal'),
    ('Siliguri, West Bengal', 'Siliguri, West Bengal'),
    ('Asansol, West Bengal', 'Asansol, West Bengal'),
    ('Hyderabad, Telangana', 'Hyderabad, Telangana'),
    ('Warangal, Telangana', 'Warangal, Telangana'),
    ('Nizamabad, Telangana', 'Nizamabad, Telangana'),
    ('Karimnagar, Telangana', 'Karimnagar, Telangana'),
    ('Khammam, Telangana', 'Khammam, Telangana'),
    ('Delhi, Delhi', 'Delhi, Delhi'),
    ('Noida, Uttar Pradesh', 'Noida, Uttar Pradesh'),
    ('Ghaziabad, Uttar Pradesh', 'Ghaziabad, Uttar Pradesh'),
    ('Lucknow, Uttar Pradesh', 'Lucknow, Uttar Pradesh'),
    ('Kanpur, Uttar Pradesh', 'Kanpur, Uttar Pradesh'),
    ('Agra, Uttar Pradesh', 'Agra, Uttar Pradesh'),
    ('Varanasi, Uttar Pradesh', 'Varanasi, Uttar Pradesh'),
    ('Meerut, Uttar Pradesh', 'Meerut, Uttar Pradesh'),
    ('Prayagraj, Uttar Pradesh', 'Prayagraj, Uttar Pradesh'),
    ('Indore, Madhya Pradesh', 'Indore, Madhya Pradesh'),
    ('Bhopal, Madhya Pradesh', 'Bhopal, Madhya Pradesh'),
    ('Jabalpur, Madhya Pradesh', 'Jabalpur, Madhya Pradesh'),
    ('Gwalior, Madhya Pradesh', 'Gwalior, Madhya Pradesh'),
    ('Ujjain, Madhya Pradesh', 'Ujjain, Madhya Pradesh'),
    ('Jaipur, Rajasthan', 'Jaipur, Rajasthan'),
    ('Jodhpur, Rajasthan', 'Jodhpur, Rajasthan'),
    ('Udaipur, Rajasthan', 'Udaipur, Rajasthan'),
    ('Kota, Rajasthan', 'Kota, Rajasthan'),
    ('Bikaner, Rajasthan', 'Bikaner, Rajasthan'),
    ('Patna, Bihar', 'Patna, Bihar'),
    ('Gaya, Bihar', 'Gaya, Bihar'),
    ('Bhagalpur, Bihar', 'Bhagalpur, Bihar'),
    ('Muzaffarpur, Bihar', 'Muzaffarpur, Bihar'),
    ('Darbhanga, Bihar', 'Darbhanga, Bihar'),
    ('Ahmedabad, Gujarat', 'Ahmedabad, Gujarat'),
    ('Surat, Gujarat', 'Surat, Gujarat'),
    ('Vadodara, Gujarat', 'Vadodara, Gujarat'),
    ('Rajkot, Gujarat', 'Rajkot, Gujarat'),
    ('Gandhinagar, Gujarat', 'Gandhinagar, Gujarat'),
    ('Chandigarh, Punjab', 'Chandigarh, Punjab'),
    ('Ludhiana, Punjab', 'Ludhiana, Punjab'),
    ('Amritsar, Punjab', 'Amritsar, Punjab'),
    ('Jalandhar, Punjab', 'Jalandhar, Punjab'),
    ('Mohali, Punjab', 'Mohali, Punjab'),
    ('Dehradun, Uttarakhand', 'Dehradun, Uttarakhand'),
    ('Haridwar, Uttarakhand', 'Haridwar, Uttarakhand'),
    ('Roorkee, Uttarakhand', 'Roorkee, Uttarakhand'),
    ('Ranchi, Jharkhand', 'Ranchi, Jharkhand'),
    ('Jamshedpur, Jharkhand', 'Jamshedpur, Jharkhand'),
    ('Dhanbad, Jharkhand', 'Dhanbad, Jharkhand'),
    ('Bhubaneswar, Odisha', 'Bhubaneswar, Odisha'),
    ('Cuttack, Odisha', 'Cuttack, Odisha'),
    ('Rourkela, Odisha', 'Rourkela, Odisha'),
    ('Raipur, Chhattisgarh', 'Raipur, Chhattisgarh'),
    ('Bilaspur, Chhattisgarh', 'Bilaspur, Chhattisgarh'),
    ('Guwahati, Assam', 'Guwahati, Assam'),
    ('Dispur, Assam', 'Dispur, Assam'),
    ('Shillong, Meghalaya', 'Shillong, Meghalaya'),
    ('Aizawl, Mizoram', 'Aizawl, Mizoram'),
    ('Imphal, Manipur', 'Imphal, Manipur'),
    ('Itanagar, Arunachal Pradesh', 'Itanagar, Arunachal Pradesh'),
    ('Kohima, Nagaland', 'Kohima, Nagaland'),
    ('Gangtok, Sikkim', 'Gangtok, Sikkim'),
    ('Port Blair, Andaman & Nicobar', 'Port Blair, Andaman & Nicobar'),
]

DISTRICT_CHOICES = [
    ('Andheri, Mumbai', 'Andheri, Mumbai'),
    ('Bandra, Mumbai', 'Bandra, Mumbai'),
    ('Dadar, Mumbai', 'Dadar, Mumbai'),
    ('Powai, Mumbai', 'Powai, Mumbai'),
    ('Hinjewadi, Pune', 'Hinjewadi, Pune'),
    ('Baner, Pune', 'Baner, Pune'),
    ('MG Road, Bengaluru', 'MG Road, Bengaluru'),
    ('Indiranagar, Bengaluru', 'Indiranagar, Bengaluru'),
    ('Koramangala, Bengaluru', 'Koramangala, Bengaluru'),
    ('T. Nagar, Chennai', 'T. Nagar, Chennai'),
    ('Anna Nagar, Chennai', 'Anna Nagar, Chennai'),
    ('Salt Lake, Kolkata', 'Salt Lake, Kolkata'),
    ('Park Street, Kolkata', 'Park Street, Kolkata'),
    ('Gachibowli, Hyderabad', 'Gachibowli, Hyderabad'),
    ('Banjara Hills, Hyderabad', 'Banjara Hills, Hyderabad'),
    ('Connaught Place, Delhi', 'Connaught Place, Delhi'),
    ('Dwarka, Delhi', 'Dwarka, Delhi'),
    ('Gomti Nagar, Lucknow', 'Gomti Nagar, Lucknow'),
    ('Hazratganj, Lucknow', 'Hazratganj, Lucknow'),
    ('Aliganj, Lucknow', 'Aliganj, Lucknow'),
    ('Kakadeo, Kanpur', 'Kakadeo, Kanpur'),
    ('Raja Park, Jaipur', 'Raja Park, Jaipur'),
    ('Bapu Nagar, Jaipur', 'Bapu Nagar, Jaipur'),
    ('Gandhi Maidan, Patna', 'Gandhi Maidan, Patna'),
    ('Boring Road, Patna', 'Boring Road, Patna'),
    ('Navrangpura, Ahmedabad', 'Navrangpura, Ahmedabad'),
    ('Satellite, Ahmedabad', 'Satellite, Ahmedabad'),
    ('Sector 17, Chandigarh', 'Sector 17, Chandigarh'),
    ('Sadar Bazar, Raipur', 'Sadar Bazar, Raipur'),
    ('Unit-4, Bhubaneswar', 'Unit-4, Bhubaneswar'),
    ('Police Bazar, Shillong', 'Police Bazar, Shillong'),
]


	PAYMENT_METHOD_CHOICES = (
		('Paypal', 'Paypal'),
		('Credit Card','Credit Card')
	)

	division = forms.ChoiceField(choices=DIVISION_CHOICES)
	district =  forms.ChoiceField(choices=DISCRICT_CHOICES)
	payment_method = forms.ChoiceField(choices=PAYMENT_METHOD_CHOICES, widget=forms.RadioSelect())

	class Meta:
		model = Order
		fields = ['name', 'email', 'phone', 'address', 'division', 'district', 'zip_code', 'payment_method', 'account_no', 'transaction_id']
